# Generated by Django 5.2.7 on 2025-10-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.CharField(default=2024, max_length=4),
            preserve_default=False,
        ),
    ]
